# Generated by Django 5.2.4 on 2025-07-30 17:11

import django.core.validators
import django.db.models.deletion
import inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la editorial')),
                ('pais', models.CharField(default='Desconocido', max_length=50, verbose_name='País de origen')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un autor con este nombre'}, help_text='Nombre completo del autor', max_length=100, unique=True, verbose_name='Nombre completo')),
                ('nacionalidad', models.CharField(blank=True, default='Desconocida', max_length=50, null=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='inicio_auto_nombre_bcb981_idx')],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título completo del libro', max_length=200, verbose_name='Título')),
                ('año_publicacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000, message='El año debe ser mayor a 1000'), django.core.validators.MaxValueValidator(inicio.models.get_current_year, message='El año no puede ser futuro')], verbose_name='Año de publicación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a 0')], verbose_name='Precio')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='inicio.autor', verbose_name='Autor')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='inicio.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-año_publicacion', 'titulo'],
                'indexes': [models.Index(fields=['titulo'], name='inicio_libr_titulo_b3ad55_idx'), models.Index(fields=['año_publicacion'], name='inicio_libr_año_pub_4baaf4_idx')],
                'unique_together': {('titulo', 'autor')},
            },
        ),
    ]
