# Generated by Django 5.2.4 on 2025-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveIndex(
            model_name='autor',
            name='inicio_auto_nombre_bcb981_idx',
        ),
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento (opcional)'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Foto del autor'),
        ),
        migrations.AddField(
            model_name='autor',
            name='premios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Premios recibidos'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='', max_length=100, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='autor',
            unique_together={('nombre', 'apellido')},
        ),
    ]
