# Generated by Django 5.2.4 on 2025-08-04 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_fix_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='fundacion',
            field=models.PositiveIntegerField(blank=True, help_text='Año de creación de la editorial (ej: 2013)', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)], verbose_name='Año de fundación'),
        ),
    ]
